# -*- coding: utf-8 -*-

# Form implementation 



#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Gui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setStyleSheet("background-color: #CFE2FF;")
        MainWindow.resize(1600, 1200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        font = QtGui.QFont()
        font.setPointSize(13)
        font2 = QtGui.QFont()
        font2.setPointSize(10)

        # (right, bottom)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 900, 760, 360))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_3.resize(800, 300)

        self.labelTesting = QtWidgets.QLabel(self.groupBox_3)
        # self.labelTesting.setGeometry(QtCore.QRect(260, 10, 101, 16))
        self.labelTesting.setGeometry(QtCore.QRect(10, 20, 760, 40))
        self.labelTesting.setObjectName("labelTesting")
        self.labelTesting.resize(300, 50)
        self.labelTesting.setFont(font2)

        self.labelInput = QtWidgets.QLabel(self.groupBox_3)
        # self.labelInput.setGeometry(QtCore.QRect(10, 70, 101, 16))
        self.labelInput.setGeometry(QtCore.QRect(10, 90, 150, 40))
        self.labelInput.resize(150, 20)
        self.labelInput.setObjectName("labelInput")

        self.labelOutput = QtWidgets.QLabel(self.groupBox_3)
        # self.labelOutput.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.labelOutput.setGeometry(QtCore.QRect(10, 140, 150, 40))
        self.labelOutput.resize(100, 20)
        self.labelOutput.setObjectName("labelOutput")

        self.buttonKlasifikasi = QtWidgets.QPushButton(self.groupBox_3)
        # self.buttonKlasifikasi.setGeometry(QtCore.QRect(475, 70, 75, 23))
        self.buttonKlasifikasi.setGeometry(QtCore.QRect(320, 200, 150, 40))
        self.buttonKlasifikasi.resize(100, 30)
        self.buttonKlasifikasi.setObjectName("buttonKlasifikasi")
        self.buttonKlasifikasi.setStyleSheet("background-color: white;")

        self.inputBox = QtWidgets.QLineEdit(self.groupBox_3)
        # self.inputBox.setGeometry(QtCore.QRect(160, 70, 241, 20))
        self.inputBox.setGeometry(QtCore.QRect(170, 90, 580, 40))
        self.inputBox.setStyleSheet("background-color: white;")
        self.inputBox.resize(400, 30)
        self.inputBox.setObjectName("inputBox")
        
        self.outputBox = QtWidgets.QLineEdit(self.groupBox_3)
        # self.outputBox.setGeometry(QtCore.QRect(160, 110, 241, 20))
        self.outputBox.setGeometry(QtCore.QRect(170, 140, 580, 40))
        self.outputBox.setStyleSheet("background-color: white;")
        self.outputBox.resize(400, 30)
        self.outputBox.setObjectName("outputBox")
        
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setGeometry(QtCore.QRect(20, 20, 760, 800))
        # self.groupBox_1.resize(400, 600)
        self.groupBox_1.setTitle("")
        self.groupBox_1.setObjectName("groupBox_1")

        self.buttonInputData = QtWidgets.QPushButton(self.groupBox_1)
        # self.buttonInputData.setGeometry(QtCore.QRect(10, 30, 75, 23))
        self.buttonInputData.setGeometry(QtCore.QRect(10, 10, 150, 40))
        self.buttonInputData.resize(120, 30)
        self.buttonInputData.setObjectName("buttonInputData")
        self.buttonInputData.setStyleSheet("background-color: white;")

        self.buttonPreprocessing = QtWidgets.QPushButton(self.groupBox_1)
        # self.buttonPreprocessing.setGeometry(QtCore.QRect(10, 60, 75, 23))
        self.buttonPreprocessing.setGeometry(QtCore.QRect(10, 60, 150, 40))
        self.buttonPreprocessing.resize(120, 30)
        self.buttonPreprocessing.setObjectName("buttonPreprocessing")
        self.buttonPreprocessing.setStyleSheet("background-color: white;")

        self.tablePreprocessing = QtWidgets.QTableWidget(self.groupBox_1)
        # self.tablePreprocessing.setGeometry(QtCore.QRect(10, 150, 471, 211))
        self.tablePreprocessing.setGeometry(QtCore.QRect(10, 110, 740, 680))
        self.tablePreprocessing.setObjectName("tablePreprocessing")
        self.tablePreprocessing.setStyleSheet("background-color: white;")
        self.tablePreprocessing.setColumnCount(0)
        self.tablePreprocessing.setRowCount(0)

        self.labelPreprocessing = QtWidgets.QLabel(self.groupBox_1)
        # self.labelPreprocessing.setGeometry(QtCore.QRect(180, 60, 161, 26))
        self.labelPreprocessing.setGeometry(QtCore.QRect(170, 60, 580, 40))
        self.labelPreprocessing.setObjectName("labelPreprocessing")
        self.labelPreprocessing.setFont(font)

        self.labelData = QtWidgets.QLabel(self.groupBox_1)
        # self.labelData.setGeometry(QtCore.QRect(140, 32, 271, 16))
        self.labelData.setGeometry(QtCore.QRect(170, 10, 580, 40))
        self.labelData.setObjectName("labelData")
        
        
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(820, 20, 760, 580))
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")

        # self.dropout = QtWidgets.QLineEdit(self.groupBox_2)
        # self.dropout.setObjectName("dropout")
        # self.hiddenUnits = QtWidgets.QLineEdit(self.groupBox_2)
        # self.hiddenUnits.setObjectName("hiddenUnits")
        # self.recurrentDropout = QtWidgets.QLineEdit(self.groupBox_2)
        # self.recurrentDropout.setObjectName("recurrentDropout")
        # self.epochs = QtWidgets.QLineEdit(self.groupBox_2)
        # self.epochs.setObjectName("epochs")
        # self.batchSize = QtWidgets.QLineEdit(self.groupBox_2)
        # self.batchSize.setObjectName("batchSize")

        self.buttonKlasifikasiModel = QtWidgets.QPushButton(self.groupBox_2)
        # self.buttonKlasifikasiModel.setGeometry(QtCore.QRect(10, 250, 85, 23))
        self.buttonKlasifikasiModel.setGeometry(QtCore.QRect(20, 545, 220, 40))
        self.buttonKlasifikasiModel.setObjectName("buttonKlasifikasiModel")
        self.buttonKlasifikasiModel.setStyleSheet("background-color: white;")

        self.labelLSTM = QtWidgets.QLabel(self.groupBox_2)
        # self.labelLSTM.setGeometry(QtCore.QRect(130, 10, 43, 18))
        self.labelLSTM.setGeometry(QtCore.QRect(10, 20, 740, 40))
        self.labelLSTM.setFont(font)

        self.textbox_dropout = QtWidgets.QLineEdit(self.groupBox_2)
        self.textbox_dropout.setGeometry(QtCore.QRect(100, 60, 83, 32))
        self.textbox_dropout.setObjectName("textbox_dropout")
        self.textbox_dropout.setStyleSheet("background-color: white;")
        self.label_dropout = QtWidgets.QLabel(self.groupBox_2)
        self.label_dropout.setGeometry(QtCore.QRect(10, 60, 83, 32))
        self.label_dropout.setText("Dropout:")
        self.label_dropout.setObjectName("label_dropout")

        self.textbox_hidden_units = QtWidgets.QLineEdit(self.groupBox_2)
        self.textbox_hidden_units.setGeometry(QtCore.QRect(320, 60, 83, 32))
        self.textbox_hidden_units.setObjectName("textbox_hidden_units")
        self.textbox_hidden_units.setStyleSheet("background-color: white;")
        self.label_hidden_units = QtWidgets.QLabel(self.groupBox_2)
        self.label_hidden_units.setGeometry(QtCore.QRect(200, 60, 113, 32))
        self.label_hidden_units.setText("Hidden units:")
        self.label_hidden_units.setObjectName("label_hidden_units")

        self.textbox_recurrent_dropout = QtWidgets.QLineEdit(self.groupBox_2)
        self.textbox_recurrent_dropout.setGeometry(QtCore.QRect(600, 60, 83, 32))
        self.textbox_recurrent_dropout.setObjectName("textbox_recurrent_dropout")
        self.textbox_recurrent_dropout.setStyleSheet("background-color: white;")
        self.label_recurrent_dropout = QtWidgets.QLabel(self.groupBox_2)
        self.label_recurrent_dropout.setGeometry(QtCore.QRect(420, 60, 183, 32))
        self.label_recurrent_dropout.setText("Recurrent dropout:")
        self.label_recurrent_dropout.setObjectName("label_recurrent_dropout")

        self.textbox_epochs = QtWidgets.QLineEdit(self.groupBox_2)
        self.textbox_epochs.setGeometry(QtCore.QRect(100, 100, 83, 32))
        self.textbox_epochs.setObjectName("textbox_epochs")
        self.textbox_epochs.setStyleSheet("background-color: white;")
        self.label_epochs = QtWidgets.QLabel(self.groupBox_2)
        self.label_epochs.setGeometry(QtCore.QRect(10, 100, 73, 32))
        self.label_epochs.setText("Epochs:")
        self.label_epochs.setObjectName("label_epochs")

        self.textbox_batch_size = QtWidgets.QLineEdit(self.groupBox_2)
        self.textbox_batch_size.setGeometry(QtCore.QRect(320, 100, 83, 32))
        self.textbox_batch_size.setObjectName("textbox_batch_size")
        self.textbox_batch_size.setStyleSheet("background-color: white;")
        self.label_batch_size = QtWidgets.QLabel(self.groupBox_2)
        self.label_batch_size.setGeometry(QtCore.QRect(200, 100, 113, 32))
        self.label_batch_size.setText("Batch size:")
        self.label_batch_size.setObjectName("label_batch_size")


        self.labelLSTM.setFont(font)

        self.labelLSTM.setObjectName("labelLSTM")
        self.tableParameter = QtWidgets.QTableWidget(self.groupBox_2)
        # self.tableParameter.setGeometry(QtCore.QRect(10, 40, 271, 201))
        self.tableParameter.setGeometry(QtCore.QRect(10, 140, 740, 400))
        self.tableParameter.setObjectName("tableParameter")
        self.tableParameter.setStyleSheet("background-color: white;")
        self.tableParameter.setColumnCount(0)
        self.tableParameter.setRowCount(0)
        
        
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(820, 610, 760, 580))
        self.groupBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")

        self.labelHammingLoss = QtWidgets.QLabel(self.groupBox_4)
        self.labelHammingLoss.setGeometry(QtCore.QRect(10, 10, 740, 50))
        self.labelHammingLoss.setObjectName("labelHammingLoss")
        self.labelHammingLoss.setFont(font) 

        self.tableHammingLoss = QtWidgets.QTableWidget(self.groupBox_4)
        # self.tableHammingLoss.setGeometry(QtCore.QRect(10, 20, 271, 191))
        self.tableHammingLoss.setGeometry(QtCore.QRect(10, 70, 740, 500)) 
        self.tableHammingLoss.setObjectName("tableHammingLoss")
        self.tableHammingLoss.setStyleSheet("background-color: white;")
        self.tableHammingLoss.setColumnCount(0)
        self.tableHammingLoss.setRowCount(0)

        self.groupBox_3.raise_()
        self.groupBox_2.raise_()
        self.groupBox_4.raise_()
        self.groupBox_1.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuKlasifikasi_Komentar_toxic = QtWidgets.QMenu(self.menubar)
        self.menuKlasifikasi_Komentar_toxic.setObjectName("menuKlasifikasi_Komentar_toxic")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuKlasifikasi_Komentar_toxic.menuAction())

        self.translateUiText(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def translateUiText(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTesting.setText(_translate("MainWindow", "Pengujian Teks"))
        self.labelInput.setText(_translate("MainWindow", "Masukkan Teks"))
        self.labelOutput.setText(_translate("MainWindow", "Hasil Teks"))
        self.labelData.setText(_translate("MainWindow", ""))
        self.buttonKlasifikasi.setText(_translate("MainWindow", "Klasifikasi"))
        self.buttonInputData.setText(_translate("MainWindow", "Input Data"))
        self.buttonPreprocessing.setText(_translate("MainWindow", "Proses Data"))
        self.labelPreprocessing.setText(_translate("MainWindow", "Hasil Preprocessing"))
        self.buttonKlasifikasiModel.setText(_translate("MainWindow", "Training Model LSTM"))
        self.labelLSTM.setText(_translate("MainWindow", "LSTM"))
        self.labelHammingLoss.setText("Hamming Loss")
        self.menuKlasifikasi_Komentar_toxic.setTitle(_translate("MainWindow", "Klasifikasi Hate Speech dan Abusive Pada Teks Menggunakan Metode LSTM"))
